name: $(BuildDefinitionName)_$(Date:yyyyMMdd)$(Rev:.rr)
variables:
  CI_NAME: Azure Pipelines
  CI_BUILD_ID: $(Build.BuildId)
  CI_BUILD_URL: "https://dev.azure.com/Cadair/parfive/_build/results?buildId=$(Build.BuildId)"

resources:
  repositories:
  - repository: OpenAstronomy
    type: github
    endpoint: Cadair
    name: OpenAstronomy/azure-pipelines-templates
    ref: master

trigger:
  branches:
    include:
    - '*'
    exclude:
    - '*backport*'
  tags:
    include:
    - 'v*'
    exclude:
    - '*dev*'
    - '*pre*'
    - '*post*'

jobs:
- template: run-tox-env.yml@OpenAstronomy
  parameters:
    envs:
      - linux: py38
        name: Linux_py38
      - windows: py36
        name: Windows_py36
      - macos: py37
        name: macos_py37

- ${{ if ne(variables['Build.Reason'], 'PullRequest') }}:
  - template: publish.yml@OpenAstronomy
    parameters:
      ${{ if startsWith(variables['Build.SourceBranch'], 'refs/tags/') }}:
        pypi_connection_name: 'PyPI'
      test_extras: ftp,test
      test_command: pytest --pyargs parfive
      targets:
        - sdist
        # - wheels_universal
      dependsOn:
        - Linux_py38
        - Windows_py36
        - macos_py37
