name: $(BuildDefinitionName)_$(Date:yyyyMMdd)$(Rev:.rr)
variables:
  CI_NAME: Azure Pipelines
  CI_BUILD_ID: $(Build.BuildId)
  CI_BUILD_URL: "https://dev.azure.com/Cadair/parfive/_build/results?buildId=$(Build.BuildId)"

resources:
  repositories:
  - repository: OpenAstronomy
    type: github
    endpoint: Cadair
    name: OpenAstronomy/azure-pipelines-templates
    ref: master

trigger:
  branches:
    include:
    - '*'
    exclude:
    - '*backport*'
  tags:
    include:
    - 'v*'
    exclude:
    - '*dev*'

stages:
  - stage: tests
    displayName: Tests
    jobs:
    - template: run-tox-env.yml@OpenAstronomy
      parameters:
        libraries:
          apt:
            - graphviz
        coverage: codecov
        envs:
          - linux: codestyle
            pytest: false

          - linux: build_docs
            pytest: false

          - linux: py38-conda

          - linux: py39

          - macos: py37

          - windows: py38

  - ${{ if ne(variables['Build.Reason'], 'PullRequest') }}:
    - stage: deploy
      displayName: Build and Release
      jobs:
        - template: publish.yml@OpenAstronomy
          parameters:
            ${{ if startsWith(variables['Build.SourceBranch'], 'refs/tags/') }}:
              pypi_connection_name: 'PyPI'
            test_extras: ftp,tests
            test_command: pytest --pyargs parfive
            targets:
              - sdist
              - wheels_universal
